### ISSUE TITLE
Showing error 

### ISSUE THREAD

**Issue by Hackff1** [AbdeLhalimSB/Youtube_Watch_Bot#1]
![IMG_20240401_182718](https://github.com/AbdeLhalimSB/Youtube_Watch_Bot/assets/89994982/bc81a476-a780-435b-86a2-70baef44c15d)
Not working

**Comment by AbdeLhalimSB** [comment]
Can you please copy & paste the error to see it clearly

**Comment by Hackff1** [comment]
I can't copy in terminal  because I am running code in Google she'll https://shell.cloud.google.com/?show=ide%2Cterminal

**Comment by AbdeLhalimSB** [comment]
Sorry Mate, Google Cloud Shell does not support running graphical applications, including web browsers like Chrome, due to its terminal-based interface.
